export const GET_STORES = 'GET_STORES';
export const CREATE_STORE_BY_NAME = 'CREATE_STORE_BY_NAME';
export const DELETE_STORE_BY_NAME = 'DELETE_STORE_BY_NAME';

export const CREATE_ITEM_BY_NAME = 'CREATE_ITEM_BY_NAME';
